Change MCT object into openmct due to TypeError
TypeError: Cannot read property 'time' of undefined
    at TelemetryAPI.standardizeRequestOptions (/home/ubuntu/openmct/src/api/telemetry/TelemetryAPI.js:9:5384)
    at TelemetryAPI.request (/home/ubuntu/openmct/src/api/telemetry/TelemetryAPI.js:9:6072)
    at jasmine.Spec.<anonymous> (/home/ubuntu/openmct/src/api/telemetry/TelemetryAPISpec.js:228:30)